### ISSUE TITLE
pouvoir visualiser la photographie d'un compteur en grand

### ISSUE THREAD

**Issue by Manu1400** [Tristramg/velos-paris#1]
1/ aller sur la page https://compteurs.parisenselle.fr/details/Boulevard-de-Sebastopol
2/ l'image affichée est téléchargée en 1920x1440

Attendu : pouvoir visualiser l'image simplement

Solution la plus simple : ajouter un lien vers https://www.eco-visio.net/Photos/100057445/15809119368880.jpg

**Comment by Tristramg** [comment]
closed by #3
