### ISSUE TITLE
Suggestion : rendre le code utilisable par d'autres villes

### ISSUE THREAD

**Issue by paulop33** [Tristramg/velos-paris#22]
Bonjour,

Merci pour ce super projet ! 
J'ai commencé hier à tester son adaptation pour le compte de Vélo-Cité, sur Bordeaux et sa métropole.

Il n'y a pas grand chose à changer : 
- créer une dictionnaire de données afin de faire correspondre les variables utilisées par les différentes AOM et celles du code (basées sur les noms du fichier csv de Paris). 
- pouvoir configurer le découpage du nom des compteurs. A Bordeaux pas de N/S O/E mais des "Vers rue de x" ou un "Sens sortant"
- pouvoir configurer le centre et le zoom de la carte depuis la config (`.env.local`)
- pas de photo des compteurs à Bordeaux dans le jeu de données de la métropole. La photo devrait être affichée uniquement si elle existe dans les datas.
- pouvoir configurer la source pour le footer

Actuellement, j'ai tous ces éléments hard-codés en local, mais je peux les rendre configurable dans le `.env.local` et faire une pull request  d'ici quelques jours. Qu'en penses-tu ?

Les assos pourront ainsi faire un fork pour s'adapter aux différentes joyeusetés locales sans avoir à comprendre tout le process d'import et de calcul des données.

A bientôt,
Paul

**Comment by Tristramg** [comment]
Bonjour,

C’est super si on arrive à utiliser le code ailleurs !

Pour tout ce qui est de mettre des variables d’environnement, aucun problème, fonce !

Je pense que le plus compliqué ça va être de faire rentrer les données et peut-être qu’il faut envisager d’avoir un script séparé pour les préparer ? J’ai peur sinon que ça devienne une bouillie (déjà que c’est pas foufou). Typiquement tout le « nettoyage » des noms est fait de manière très à l’arrache en fonction des problèmes qui apparaissent
