### ISSUE TITLE
Quai-d'Issy page leads to 404

### ISSUE THREAD

**Issue by gturri** [Tristramg/velos-paris#5]
**Steps to reproduce :**
- go to https://compteurs.parisenselle.fr
- on the map click on the "quai d'issy" marker, and then on "Voir les détails". It leads to the page https://compteurs.parisenselle.fr/details/Quai-d'Issy

**Expected behavior :** the page https://compteurs.parisenselle.fr/details/Quai-d'Issy results in a html 200 status

**Actual behavior :** the page https://compteurs.parisenselle.fr/details/Quai-d'Issy results in a html 404 status

**Miscellaneous information**
- If on https://compteurs.parisenselle.fr/ you scroll to the "Quai d’Issy" tile and click on the "Voir la fréquentation détaillée " link, then the page url is changed to https://compteurs.parisenselle.fr/details/Quai-d'Issy and the data is correctly displayed (but if you refresh the page afterward, you still get a 404)
- I'm noticing this issue occurs also with those locations: `quai d'orsay`, `avenue de la porte d'orléans`, `rue d'aubervillier`, `quai d'austerlitz`, so I suspect it might be related to a bad handling of a quote (') in the endpoint name

**Comment by Tristramg** [comment]
Thank you for the detailed report, it was easy to spot were the bug was!
