### ISSUE TITLE
Calendar heatmap github style

### ISSUE THREAD

**Issue by m4nu56** [Tristramg/velos-paris#9]
J'imaginerais bien intégrer un composant un peu comme les calendriers heatmap d'activité sur github/gitlab pour chaque totem.
J'ai trouvé ce composant qui pourrait faire l'affaire: 
https://github.com/kevinsqi/react-calendar-heatmap
Ça te dit que j'essaie d'intégrer ça au projet pour voir ce que ça donne ?

**Comment by Tristramg** [comment]
Ça peut être super intéressant pour voir les phénomènes hebdomadaires en effet !

La lib utilisée pour les autres graphes semble le faire : https://vega.github.io/vega-lite/docs/rect.html
La syntaxe peut être un peu déroutante des fois, pour ma part j’aime bien utiliser le « open in vega editor » en haut à droite de chaque graphe pour expérimenter un peu.

Il faudra également générer des données moins aggrégées (un chiffre par jour pendant un an).

Tu te sens de te lancer tel quel ou ça pourrait aider si je prépare quelques trucs ?

**Comment by m4nu56** [comment]
Alors j'ai avancé un peu. J'ai modifié le json de chaque avenue pour ajouter un nouveau type `year_daily` avec le cumul de passage a chaque totem pour chaque jour de la dernière année. 

Et je me sert de ces données dans le nouveau composant `Heatmap` où je fais un cumul par jour pour avoir les passages dans chaque sens de circulation. 
Est-ce que ça te parait bien ou tu veux qu'on essaie de séparer les sens d'une manière ou d'une autre ?

![image](https://user-images.githubusercontent.com/330472/95681866-6fbb6a80-0be2-11eb-8976-debd0b42aa94.png)
